export {
	OutputCollisionError,
	type RenderSpineError,
	RenderOptionValidationError,
	SpineInputResolutionError,
	SpineSelectionError,
	type OutputCollisionErrorCode,
	type RenderOptionValidationErrorCode,
	type SpineInputAssetType,
	type SpineInputResolutionErrorCode,
	type SpineSelectionErrorCode,
	type SpineSelectionType,
	isOutputCollisionError,
	isRenderOptionValidationError,
	isRenderSpineError,
	isSpineInputResolutionError,
	isSpineSelectionError,
} from "./lib/errors.ts";
export {
	type OutputFormat,
	renderSpine,
	renderSpineToApng,
	type RenderSpineOptions,
	type RenderSpineResult,
} from "#/render-spine.ts";
